name: star-rsem
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.6
    - pandas 

    - star=2.7.3a
    - rsem=1.3.1

    - pip
    - pip:
        - snakemake==5.8.2
